### ISSUE TITLE
Understanding this plugin

### ISSUE THREAD

**Issue by reg-is** [PJCzx/homebridge-window-cover#2]
I'm having problems understanding this plugin.
It works fine for me to run a python script. But I need to run a different script for opening and closing the window covers.
What are the "id" and "apiroute" in the config.json for?

**Comment by PJCzx** [comment]
Can't you merge your scripts and manage this with a parameter as defined in the exemple ? 

API route is for API usage not python script one

**Comment by PJCzx** [comment]
Closed since ne feedback.

Best,
pjcazaux
